export const AuthKey = 'access-token' // 本地存储Token的Key名称
export const LoginRouteKey = 'LoginIndex' // 登录页的Name
export const NotFoundRouteKey = 'NotFound' // 404页面的Name
export const SystemHomeKey = 'AboutPageIndex' // 系统首页的Name
export const ThemeKey = 'theme'
export const ThemePrimaryColorKey = 'primary-color'
export const TabMenuKey = 'tab-menu'
export const DefaultMenuIcon = 'Person' // 默认菜单图标
export const LocalSystemConfigKey = 'local-system-config' // 本地系统配置
